[build]
  # Esse comando obriga a instalaÃ§Ã£o do Vite e corrige a falta de dependencias
  command = "npm install --include=dev && npm run build"
  
  # Pasta de saÃ­da
  publish = "dist"
  
  # Pasta das funÃ§Ãµes
  functions = "netlify/functions"

[build.environment]
  # ğŸ”´ A CURA DO ERRO /dev/null ğŸ”´
  # Isso forÃ§a o npm a usar uma pasta vÃ¡lida para o cache
  NPM_CONFIG_CACHE = "/opt/build/repo/node_modules/.npm"
  NODE_VERSION = "20"