[build]
  # Comando força a instalação das ferramentas de dev (Vite)
  command = "npm install --include=dev && npm run build"
  
  # Pasta onde o site pronto vai ficar (Vite usa dist)
  publish = "dist"
  
  # Pasta das functions
  functions = "netlify/functions"

[build.environment]
  # Força o cache a ficar numa pasta válida, corrigindo o erro do /dev/null
  NPM_CONFIG_CACHE = "node_modules/.cache"
  NODE_VERSION = "20"